1408: Create a workflow that will run the script to get the latest version and send in a slack notification

diff --git a/.github/workflows/create-rc-release.yml b/.github/workflows/create-rc-release.yml
--- a/.github/workflows/create-rc-release.yml
+++ b/.github/workflows/create-rc-release.yml
@@ -16,8 +16,24 @@ jobs:
     name: Build
     runs-on: ubuntu-latest
     steps:
+      # Checkout Code
+      - name: Checkout CI Repo
+        uses: actions/checkout@v4
+        with:
+          path: secure-api-gateway-ci
+          repository: SecureApiGateway/secure-api-gateway-ci
+      # Auth GCP, SDK & Artifact Registry
+      - name: Authentication
+        uses: ./secure-api-gateway-ci/.github/actions/authentication
+        with:
+          gcpKey: ${{ secrets.gcpKey }}
+          garLocation: ${{ inputs.garLocation }}
+      # Get Webhook from GSM
+      - name: Get Webhook URL from GSM
+        run: |
+          echo "SLACK_WEBHOOK=$(gcloud --project ${{ vars.SAPIG_PROJECT }} secrets versions access latest --secret=${{ vars.GSM_NOTIFY_WEBOOK_NAME }})" >> $GITHUB_ENV
       # Prepare Environment
-      - name: Prepare Environment
+      - name: Get Next Release Version
         run: |
           sapigType=$(echo "${{ inputs.sapigType }}" | tr "[:upper:]" "[:lower:]")
           if [ "$sapigType" != "core" ] && [ "$sapigType" != "ob" ]; then
@@ -32,3 +48,5 @@ jobs:
             components="IG RCS RS RCSUI TDI FUNC DCR"
           fi
           versionToUse=$(./scripts/docker-get-max-rc-version.sh "$components" "$versionToChange" )
+          slackMessage="The next available version to use for a ${{ inputs.versionToChange }} release is : $versionToUse"
+          curl -X POST -H "Content-type: application/json" --data '{"text": "'"$slackMessage"'"}' "${{ env.SLACK_WEBHOOK }}" || echo "ERROR - Could not send message"
