1481: Initial changes for building V# images

diff --git a/.github/workflows/reusable-merge.yml b/.github/workflows/reusable-merge.yml
--- a/.github/workflows/reusable-merge.yml
+++ b/.github/workflows/reusable-merge.yml
@@ -14,6 +14,10 @@ on:
         description: The SAPIG Type for the component (optional)
         required: false
         type: string
+      componentBranch:
+        description: The repository branch for component (optional)
+        required: false
+        type: string
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -34,9 +38,24 @@ jobs:
       # Prepare Environment
       - name: Prepare Environment
         run: |
+          # What Docker Tag to build
           if grep -q TAG_REPLACE secure-api-gateway-ci/component-config/${{ inputs.componentName }}.env; then
             sed -i -e 's/TAG_REPLACE/'${{ inputs.dockerTag }}'/g' secure-api-gateway-ci/component-config/${{ inputs.componentName }}.env
           fi
+          # We may have more than one 'main' branch active at one time, need to be able to identify the different branches and create different 'latest' docker tags 
+          if [[ "${{ inputs.componentBranch }}" ]]; then
+            if [[ "${{ inputs.componentBranch }}" =~ v[0-9] ]]; then
+              # Only going up to v999, should be more than enough as only on v4 at time of writing
+              branch=$(echo ${{ inputs.componentBranch }} | grep -oP "v[0-9]{1,3}") 
+              sed -i -e 's/LATESTTAG_REPLACE/'latest-$branch}'/g' secure-api-gateway-ci/component-config/${{ inputs.componentName }}.env
+            elif [[ "$branch" == "main" || "$branch" == "master" ]]; then
+              sed -i -e 's/LATESTTAG_REPLACE/'latest}'/g' secure-api-gateway-ci/component-config/${{ inputs.componentName }}.env
+            else
+              echo "ERROR: Unknown branch"
+              exit 1
+            fi
+          fi
+          # Once all replacements are done, load all the variables in the .env file to github
           grep -v '^#' secure-api-gateway-ci/component-config/${{ inputs.componentName }}.env >> $GITHUB_ENV
       # Auth GCP, SDK & Artifact Registry
       - name: Authentication
