1548: Add in pre merge checks

diff --git a/.github/workflows/reusable-pr.yml b/.github/workflows/reusable-pr.yml
--- a/.github/workflows/reusable-pr.yml
+++ b/.github/workflows/reusable-pr.yml
@@ -249,3 +249,38 @@ jobs:
           cfPipelineBranch: ${{ env.CF_PIPELINE_BRANCH }}
           dockerTag: ${{ inputs.dockerTag }}
           serviceName: pr/${{ env.SERVICE_NAME }}
+  pre-merge:
+    runs-on: ubuntu-latest
+    name: Pre Merge Checks
+    needs: deploy
+    if: always() && !cancelled() && !contains(needs.*.result, 'failure')
+    steps:
+      # Checkout CI Repo
+      - name: Checkout CI Repo
+        uses: actions/checkout@v4
+        with:
+          path: secure-api-gateway-ci
+          repository: SecureApiGateway/secure-api-gateway-ci
+      # Checkout Calling Repo
+      - name: Checkout Calling Repo
+        uses: actions/checkout@v4
+        with:
+          path: ${{ inputs.componentName }}
+          repository: SecureApiGateway/${{ inputs.componentName }}
+      # Prepare Environment
+      - name: Prepare Environment
+        run: |
+          if [ -n ${{ inputs.sapigType }} ]; then
+            echo "SAPIG_TYPE=${{ inputs.sapigType }}" >> $GITHUB_ENV
+          fi
+          grep -v '^#' secure-api-gateway-ci/component-config/${{ inputs.componentName }}.env >> $GITHUB_ENV
+      # PR Artifacts Build
+      - name: Check for PR Artifacts
+        run: |
+          pomVersion=$(cd ${{ inputs.componentName }} && mvn help:evaluate -Dexpression=revision -q -DforceStdout)
+          commonBomVersion=$(cd ${{ inputs.componentName }} && mvn help:evaluate -Dexpression=uk.bom.version -q -DforceStdout)
+          rsConsentVersion=$(cd ${{ inputs.componentName }} && mvn help:evaluate -Dexpression=consent.api.version -q -DforceStdout)
+          if [[ "$pomVersion" =~ "pr-" || "$commonBomVersion" =~ "pr-" || "$rsConsentVersion" =~ "pr-" ]]; then
+            echo "Error: PR Atrifact version detected, failing the pre merge checks"
+            exit 1
+          fi
