1389: Making a comparison before the envs are set

diff --git a/.github/workflows/reusable-release.yml b/.github/workflows/reusable-release.yml
--- a/.github/workflows/reusable-release.yml
+++ b/.github/workflows/reusable-release.yml
@@ -41,11 +41,6 @@ jobs:
       # Prepare Environment
       - name: Prepare Environment
         run: |
-          # STEPS_RELEASE_PREPARE_MAVEN_PROJECT & STEPS_RELEASE_PREPARE_TAG_MANUALLY Cannot both be true
-          if [ "${{ inputs.STEPS_RELEASE_PREPARE_MAVEN_PROJECT }}" == "${{ inputs.STEPS_RELEASE_PREPARE_TAG_MANUALLY }}" ]; then
-            echo "ERROR: STEPS_RELEASE_PREPARE_MAVEN_PROJECT & STEPS_RELEASE_PREPARE_TAG_MANUALLY Cannot both be true or false"
-            exit 1
-          fi
           if grep -q NOTES_REPLACE secure-api-gateway-ci/component-config/${{ inputs.componentName }}.env; then
             sed -i -e 's/NOTES_REPLACE/'v${{ inputs.releaseNotes }}'/g' secure-api-gateway-ci/component-config/${{ inputs.componentName }}.env
           fi
@@ -59,6 +54,10 @@ jobs:
             sed -i -e 's/VERSION_REPLACE/'v${{ inputs.releaseVersion }}'/g' secure-api-gateway-ci/component-config/${{ inputs.componentName }}.env
           fi
           grep -v '^#' secure-api-gateway-ci/component-config/${{ inputs.componentName }}.env >> $GITHUB_ENV
+          if [ "${{ inputs.STEPS_RELEASE_PREPARE_MAVEN_PROJECT }}" == "${{ inputs.STEPS_RELEASE_PREPARE_TAG_MANUALLY }}" ]; then
+            echo "ERROR: STEPS_RELEASE_PREPARE_MAVEN_PROJECT & STEPS_RELEASE_PREPARE_TAG_MANUALLY Cannot both be true or false"
+            exit 1
+          fi
       # Auth GCP, SDK & Artifact Registry
       - name: Authentication
         uses: ./secure-api-gateway-ci/.github/actions/authentication
