OpenIG-9949: Add else to case

diff --git a/.github/workflows/reusable-release.yml b/.github/workflows/reusable-release.yml
--- a/.github/workflows/reusable-release.yml
+++ b/.github/workflows/reusable-release.yml
@@ -206,6 +206,10 @@ jobs:
               component="securebanking-test-data-initializer"
               itssComponent="secure-api-gateway-test-data-initializer"
               ;;
+            *)
+              echo "ERROR: Component not expected, please check"
+              exit 1
+              ;;
           if [ -z "$(docker images -q ${{ vars.GAR_RELEASE_REPO }}/securebanking/$component:${{ vars.VERSION_REPLACE }} 2> /dev/null)" ]; then
             # Tag image for ITSS repo
             docker tag ${{ vars.GAR_RELEASE_REPO }}/securebanking/$component:${{ vars.VERSION_REPLACE }} ${{ vars.ITSS_GAR_RELEASE_REPO }}/base/securebanking/$itssComponent:${{ vars.VERSION_REPLACE }}
